### ISSUE TITLE
Meta feedback re: slides/links/etc

### ISSUE THREAD

**Issue by apreshill** [jennybc/wtf-2018-seattle#13]
I think it would be helpful at the beginning of each slide deck to have:

1. Link to the slides (note that when the PDF version is viewed through GitHub online, links are not clickable or copy/paste-able, which got a little tiresome)
1. Long form link to the relevant [WTF](https://whattheyforgot.org/) / [Happy Git with R](http://happygitwithr.com/) section materials
1. How to access the activities (whether it is a `use_course` or a link to elsewhere)
     - If `use_course`, what the resulting R Project file that is created is named (i.e., here is my workspace- it was hard to remember which units each project came from)
<img width="287" alt="screen shot 2018-10-23 at 1 23 08 pm" src="https://user-images.githubusercontent.com/12160301/47388387-db8b2c80-d6c6-11e8-9a29-5ccb6f0c6637.png">

**Comment by jennybc** [comment]
We've been very intentional about centralization and links for rstudio::conf. Fingers crossed that this aspect is much smoother.
