### ISSUE TITLE
Feedback on Day 1, unit 1

### ISSUE THREAD

**Issue by apreshill** [jennybc/wtf-2018-seattle#8]
Hi @jennybc and @jimhester,

This feedback relates to the following set of materials:

- [Slides](https://github.com/jennybc/whattheyforgot-seattle/blob/master/day1_slides1_projects-and-paths.pdf)
- Activities: `usethis::use_course("rstd.io/wtf-1")`
      - Note this creates an R project called `day1_s1_explore-libraries`

This unit went pretty smooth from my perspective. It was helpful to use the `use_course` function. My only comment was that I think `dplyr::glimpse()` is a really helpful function to recommend in the exercises. I saw a number of folks struggling with how to view the tibbles they created in the console. I can add this as a PR but wasn't sure where the actual source for those materials lived.

That was my only note for this unit!

**Comment by jennybc** [comment]
Added `dplyr::glimpse()` to the "comfy" prompt.
